# -*- coding: utf-8 -*-
"""AutomationTestingMultiAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k0ATvzBMN2sULjq7Q7rQdjqb8SiOIw8X
"""

!pip install anthropic openai pdfplumber python-docx transformers torch huggingface_hub

!pip install docling

"""
Document to Test Requirements Pipeline
Flow: input doc -> parse -> chunk -> analyze (unstructured -> structured JSON)
"""

import os
import json
import re
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Optional


# ─────────────────────────────────────────────
# LLM CLIENT ABSTRACTION
# ─────────────────────────────────────────────

class LLMClient(ABC):
    """Abstract base — implement this to plug in any LLM backend."""

    @abstractmethod
    def complete(self, system: str, user: str) -> str:
        """Send system + user prompt, return raw text response."""
        ...


class AnthropicClient(LLMClient):
    """Claude via Anthropic API."""

    def __init__(self, model: str = "claude-sonnet-4-6", api_key: Optional[str] = None):
        import anthropic
        self.model = model
        self.client = anthropic.Anthropic(api_key=api_key or os.environ.get("ANTHROPIC_API_KEY"))

    def complete(self, system: str, user: str) -> str:
        response = self.client.messages.create(
            model=self.model,
            max_tokens=2048,
            system=system,
            messages=[{"role": "user", "content": user}],
        )
        return response.content[0].text.strip()


class OpenAIClient(LLMClient):
    """OpenAI-compatible API (OpenAI, Azure, Together, Groq, vLLM, LM Studio…)."""

    def __init__(
        self,
        model: str = "gpt-4o",
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,  # override for local/custom endpoints
    ):
        from openai import OpenAI
        self.model = model
        self.client = OpenAI(
            api_key=api_key or os.environ.get("OPENAI_API_KEY", "no-key"),
            base_url=base_url,  # e.g. "http://localhost:11434/v1" for Ollama
        )

    def complete(self, system: str, user: str) -> str:
        response = self.client.chat.completions.create(
            model=self.model,
            max_tokens=2048,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        )
        return response.choices[0].message.content.strip()


class OllamaClient(OpenAIClient):
    """Ollama local models — thin wrapper over OpenAIClient with preset base_url."""

    def __init__(self, model: str = "llama3", host: str = "http://localhost:11434"):
        super().__init__(model=model, api_key="ollama", base_url=f"{host}/v1")


class HuggingFaceClient(LLMClient):
    """
    HuggingFace Inference — local pipeline hoặc Inference API.

    Local (chạy model trên máy):
        client = HuggingFaceClient(model="ibm-granite/granite-3.0-2b-instruct")

    HF Inference API (chạy trên cloud HF, cần token):
        client = HuggingFaceClient(
            model="ibm-granite/granite-3.0-2b-instruct",
            use_api=True,
            api_key="hf_...",
        )

    Yêu cầu:
        pip install transformers torch          # local
        pip install huggingface_hub             # API
    """

    def __init__(
        self,
        model: str = "ibm-granite/granite-3.0-2b-instruct",
        api_key: Optional[str] = None,
        use_api: bool = False,
        max_new_tokens: int = 2048,
        device: Optional[str] = None,  # "cpu" | "cuda" | "mps" | None = auto
    ):
        self.model_id = model
        self.use_api = use_api
        self.api_key = api_key or os.environ.get("HF_TOKEN")
        self.max_new_tokens = max_new_tokens
        self.device = device
        self._pipeline = None   # lazy-load khi gọi complete() lần đầu

    def _get_pipeline(self):
        """Lazy-load local transformers pipeline."""
        if self._pipeline is not None:
            return self._pipeline

        try:
            import torch
            from transformers import pipeline, AutoTokenizer
        except ImportError:
            raise ImportError("Install: pip install transformers torch")

        # Auto-detect device nếu không truyền vào
        if self.device:
            device = self.device
        elif torch.cuda.is_available():
            device = "cuda"
        elif torch.backends.mps.is_available():
            device = "mps"
        else:
            device = "cpu"

        print(f"   🤗 Loading {self.model_id} on {device}...")
        tokenizer = AutoTokenizer.from_pretrained(self.model_id)
        self._pipeline = pipeline(
            "text-generation",
            model=self.model_id,
            tokenizer=tokenizer,
            device=device,
            torch_dtype=torch.float16 if device != "cpu" else torch.float32,
        )
        return self._pipeline

    def _format_prompt(self, system: str, user: str) -> str:
        """
        Granite 3.0 dùng chat template chuẩn.
        Dùng tokenizer.apply_chat_template nếu có, fallback sang string format.
        """
        try:
            from transformers import AutoTokenizer
            tokenizer = AutoTokenizer.from_pretrained(self.model_id)
            messages = [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ]
            # add_generation_prompt=True để model biết phải generate tiếp
            return tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )
        except Exception:
            # Fallback nếu tokenizer không có chat template
            return f"<|system|>\n{system}\n<|user|>\n{user}\n<|assistant|>\n"

    def complete(self, system: str, user: str) -> str:
        if self.use_api:
            return self._complete_via_api(system, user)
        return self._complete_local(system, user)

    def _complete_local(self, system: str, user: str) -> str:
        pipe = self._get_pipeline()
        prompt = self._format_prompt(system, user)

        outputs = pipe(
            prompt,
            max_new_tokens=self.max_new_tokens,
            do_sample=False,            # greedy — output ổn định hơn cho JSON
            return_full_text=False,     # chỉ trả phần generated, không lặp lại prompt
        )
        return outputs[0]["generated_text"].strip()

    def _complete_via_api(self, system: str, user: str) -> str:
        try:
            from huggingface_hub import InferenceClient
        except ImportError:
            raise ImportError("Install: pip install huggingface_hub")

        hf_client = InferenceClient(model=self.model_id, token=self.api_key)
        messages = [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ]
        response = hf_client.chat_completion(
            messages=messages,
            max_tokens=self.max_new_tokens,
        )
        return response.choices[0].message.content.strip()


# ─────────────────────────────────────────────
# STEP 1: DOCUMENT PARSING
# ─────────────────────────────────────────────

def parse_document(file_path: str) -> str:
    """
    Parse document to plain text.
    Supports: .txt, .md, .pdf, .docx
    Uses docling if available, falls back to basic parsers.
    """
    ext = Path(file_path).suffix.lower()

    # Try docling first (best quality, handles complex layouts)
    try:
        from docling.document_converter import DocumentConverter
        converter = DocumentConverter()
        result = converter.convert(file_path)
        return result.document.export_to_markdown()
    except ImportError:
        pass  # Fallback to basic parsers

    if ext in [".txt", ".md"]:
        with open(file_path, "r", encoding="utf-8") as f:
            return f.read()

    elif ext == ".pdf":
        try:
            import pdfplumber
            text = ""
            with pdfplumber.open(file_path) as pdf:
                for page in pdf.pages:
                    text += page.extract_text() or ""
            return text
        except ImportError:
            raise ImportError("Install pdfplumber: pip install pdfplumber")

    elif ext == ".docx":
        try:
            import docx
            doc = docx.Document(file_path)
            return "\n".join(p.text for p in doc.paragraphs if p.text.strip())
        except ImportError:
            raise ImportError("Install python-docx: pip install python-docx")

    else:
        raise ValueError(f"Unsupported file type: {ext}")


# ─────────────────────────────────────────────
# STEP 2: CHUNKING
# ─────────────────────────────────────────────

def chunk_document(text: str, chunk_size: int = 1500, overlap: int = 200) -> list[str]:
    """
    Split document into overlapping chunks.
    Tries to split on section boundaries (##, Heading) first.
    Falls back to character-level sliding window.
    """
    # Try semantic splitting by section headers
    section_pattern = re.compile(
        r"(?=(?:#{1,3}\s|\n[A-Z][^\n]{0,80}\n[-=]{3,}|\n\d+\.\s+[A-Z]))",
        re.MULTILINE
    )
    sections = section_pattern.split(text)
    sections = [s.strip() for s in sections if s.strip()]

    chunks = []
    buffer = ""

    for section in sections:
        if len(buffer) + len(section) <= chunk_size:
            buffer += "\n\n" + section
        else:
            if buffer:
                chunks.append(buffer.strip())
            # If single section is too large, do sliding window
            if len(section) > chunk_size:
                for i in range(0, len(section), chunk_size - overlap):
                    chunks.append(section[i : i + chunk_size].strip())
            else:
                buffer = section

    if buffer.strip():
        chunks.append(buffer.strip())

    return chunks if chunks else [text]


# ─────────────────────────────────────────────
# STEP 3: ANALYSIS (Unstructured → Structured)
# ─────────────────────────────────────────────

SYSTEM_PROMPT = """You are a senior QA engineer. Your job is to extract test requirements from documentation.

For each requirement or feature described, output a JSON object with this exact structure:
{
  "requirement_id": "REQ-<MODULE>-<NUMBER>",  // e.g. REQ-LOGIN-01
  "type": "API" or "UI",                       // API if involves endpoints/backend, UI if involves user interface
  "description": "short description under 100 words",
  "url": "url of route"
  "rules": [
    "validation rule 1",
    "validation rule 2"
  ]
}

Return a JSON array of all requirements found. If no clear requirements exist, return [].
Output ONLY valid JSON, no markdown, no explanation."""

def analyze_chunk(client: LLMClient, chunk: str, chunk_index: int) -> list[dict]:
    """Send a chunk to any LLMClient and extract structured requirements."""
    try:
        raw = client.complete(
            system=SYSTEM_PROMPT,
            user=f"Extract test requirements from this documentation chunk:\n\n{chunk}",
        )
        # Strip markdown code fences if present
        raw = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw, flags=re.MULTILINE).strip()

        requirements = json.loads(raw)
        if isinstance(requirements, dict):
            requirements = [requirements]

        # Tag each requirement with source chunk
        for req in requirements:
            req["_source_chunk"] = chunk_index

        return requirements

    except (json.JSONDecodeError, KeyError) as e:
        print(f"  ⚠️  Chunk {chunk_index}: Failed to parse response — {e}")
        return []


def deduplicate_requirements(requirements: list[dict]) -> list[dict]:
    """Remove duplicate requirement IDs, renumber if needed."""
    seen_ids = {}
    result = []

    for req in requirements:
        req_id = req.get("requirement_id", "REQ-UNKNOWN-00")
        if req_id not in seen_ids:
            seen_ids[req_id] = True
            result.append(req)
        else:
            # Renumber duplicate
            base = re.sub(r"-\d+$", "", req_id)
            counter = 2
            while f"{base}-{counter:02d}" in seen_ids:
                counter += 1
            new_id = f"{base}-{counter:02d}"
            seen_ids[new_id] = True
            req["requirement_id"] = new_id
            result.append(req)

    return result


def clean_requirements(requirements: list[dict]) -> list[dict]:
    """Remove internal metadata fields before final output."""
    cleaned = []
    for req in requirements:
        cleaned.append({k: v for k, v in req.items() if not k.startswith("_")})
    return cleaned


# ─────────────────────────────────────────────
# MAIN PIPELINE
# ─────────────────────────────────────────────

def run_pipeline(
    file_path: str,
    output_path: Optional[str] = None,
    chunk_size: int = 1500,
    overlap: int = 200,
    client: Optional[LLMClient] = None,
) -> list[dict]:
    """
    Full pipeline: document -> structured test requirements.

    Args:
        file_path:   Path to input document (.txt, .md, .pdf, .docx)
        output_path: Optional path to save JSON output
        chunk_size:  Characters per chunk (default 1500)
        overlap:     Overlap between chunks (default 200)
        client:      LLMClient instance. Defaults to AnthropicClient (claude-sonnet-4-6)

    Returns:
        List of structured requirement dicts
    """
    client = client or AnthropicClient()

    print(f"📄 Parsing document: {file_path}")
    text = parse_document(file_path)
    print(f"   Extracted {len(text):,} characters")

    print(f"✂️  Chunking document...")
    chunks = chunk_document(text, chunk_size=chunk_size, overlap=overlap)
    print(f"   Created {len(chunks)} chunks")

    print(f"🧠 Analyzing chunks with Claude...")
    all_requirements = []
    for i, chunk in enumerate(chunks):
        print(f"   Chunk {i+1}/{len(chunks)}...", end=" ")
        reqs = analyze_chunk(client, chunk, chunk_index=i)
        print(f"found {len(reqs)} requirement(s)")
        all_requirements.extend(reqs)

    print(f"🔧 Post-processing...")
    all_requirements = deduplicate_requirements(all_requirements)
    all_requirements = clean_requirements(all_requirements)

    print(f"✅ Done! Extracted {len(all_requirements)} requirements total.")

    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(all_requirements, f, indent=2, ensure_ascii=False)
        print(f"💾 Saved to: {output_path}")

    return all_requirements

# import os

# # Replace "YOUR_HF_TOKEN" with your actual Hugging Face token
# os.environ["HF_TOKEN"] = "YOUR_HF_TOKEN"

# print("HF_TOKEN environment variable set.")

# ─────────────────────────────────────────────
# RUN
# ─────────────────────────────────────────────

if __name__ == "__main__":
    # ── Pick one client ──────────────────────────────────────

    # Claude (default)
    # client = AnthropicClient(model="claude-sonnet-4-6")

    # GPT-4o
    # client = OpenAIClient(model="gpt-4o")

    # Ollama local (llama3, mistral, gemma…)
    # client = OllamaClient(model="llama3")

    # vLLM / LM Studio / bất kỳ OpenAI-compatible endpoint
    # client = OpenAIClient(model="mistral-7b", base_url="http://localhost:8000/v1")

    # HuggingFace local (chạy trực tiếp trên máy, không cần internet sau lần đầu)
    client = HuggingFaceClient(model="ibm-granite/granite-3.0-2b-instruct")

    # HuggingFace Inference API (cloud HF, cần HF_TOKEN)
    # client = HuggingFaceClient(model="ibm-granite/granite-3.0-2b-instruct", use_api=True)

    # ─────────────────────────────────────────

    requirements = run_pipeline(
        file_path="/content/api_documentation.md",
        output_path="/content/output.json",   # None = không save file
        chunk_size=1500,
        overlap=200,
        client=client,
    )

    print("\n📋 Sample output (first 2 requirements):")
    print(json.dumps(requirements[:2], indent=2, ensure_ascii=False))