"""Add fenced Vision operations and immutable locator handoffs.

Revision ID: f9a0b1c2d3e4
Revises: f8a9b0c1d2e3
"""

import sqlalchemy as sa
from alembic import op

revision = "f9a0b1c2d3e4"
down_revision = "f8a9b0c1d2e3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_visual_session_scope", "visual_exploration_sessions", ["tenant_id", "project_id", "id"]
    )
    op.add_column(
        "visual_exploration_sessions",
        sa.Column("trace_version", sa.String(length=20), server_default="legacy", nullable=False),
    )
    op.add_column("visual_exploration_sessions", sa.Column("lease_owner", sa.Uuid(), nullable=True))
    op.add_column(
        "visual_exploration_sessions",
        sa.Column("fencing_token", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "visual_exploration_sessions",
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "visual_exploration_sessions",
        sa.Column("next_operation_sequence", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column("visual_exploration_states", sa.Column("checkpoint", sa.JSON(), nullable=True))
    op.create_table(
        "visual_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("state_id", sa.Uuid(), nullable=True),
        sa.Column("proposal_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("fencing_token", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("tenant_id", sa.String(length=200), nullable=False),
        sa.CheckConstraint("sequence > 0 AND attempt > 0", name="ck_visual_operation_sequence"),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["visual_action_proposals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["visual_exploration_states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "project_id", "session_id"],
            [
                "visual_exploration_sessions.tenant_id",
                "visual_exploration_sessions.project_id",
                "visual_exploration_sessions.id",
            ],
            name="fk_visual_operation_session",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "session_id", "id", name="uq_visual_operation_scope"),
        sa.UniqueConstraint(
            "tenant_id", "session_id", "proposal_id", "attempt", name="uq_visual_operation_attempt"
        ),
        sa.UniqueConstraint(
            "tenant_id", "session_id", "sequence", name="uq_visual_operation_sequence"
        ),
    )
    op.create_index(
        op.f("ix_visual_operations_tenant_id"), "visual_operations", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_visual_operations_timeline",
        "visual_operations",
        ["tenant_id", "project_id", "session_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "visual_operation_frames",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("byte_count", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.String(length=200), nullable=False),
        sa.CheckConstraint("role IN ('before', 'after')", name="ck_visual_operation_frame_role"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id", "operation_id"],
            ["visual_operations.tenant_id", "visual_operations.session_id", "visual_operations.id"],
            name="fk_visual_operation_frame_operation",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation_id", "role", name="uq_visual_operation_frame_role"),
        sa.UniqueConstraint(
            "tenant_id", "session_id", "id", name="uq_visual_operation_frame_scope"
        ),
    )
    op.create_index(
        "ix_visual_operation_frames_session",
        "visual_operation_frames",
        ["tenant_id", "project_id", "session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_visual_operation_frames_tenant_id"),
        "visual_operation_frames",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "visual_locator_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("originating_frame_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("tenant_id", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["visual_action_proposals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["visual_exploration_states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id", "operation_id"],
            ["visual_operations.tenant_id", "visual_operations.session_id", "visual_operations.id"],
            name="fk_visual_locator_operation",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id", "originating_frame_id"],
            [
                "visual_operation_frames.tenant_id",
                "visual_operation_frames.session_id",
                "visual_operation_frames.id",
            ],
            name="fk_visual_locator_frame",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_visual_locator_evidence_tenant_id"),
        "visual_locator_evidence",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_visual_locator_session",
        "visual_locator_evidence",
        ["tenant_id", "project_id", "session_id"],
        unique=False,
    )
    op.create_table(
        "visual_locator_handoffs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generation_request_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "project_id", "session_id"],
            [
                "visual_exploration_sessions.tenant_id",
                "visual_exploration_sessions.project_id",
                "visual_exploration_sessions.id",
            ],
            name="fk_visual_handoff_session",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "session_id", "version", name="uq_visual_handoff_version"),
    )
    op.create_index(
        "ix_visual_handoff_generation",
        "visual_locator_handoffs",
        ["tenant_id", "project_id", "generation_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_visual_locator_handoffs_tenant_id"),
        "visual_locator_handoffs",
        ["tenant_id"],
        unique=False,
    )
    op.add_column("generation_requests", sa.Column("vision_handoff_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_generation_vision_handoff",
        "generation_requests",
        "visual_locator_handoffs",
        ["vision_handoff_id"],
        ["id"],
    )
    op.create_index(
        "ix_generation_requests_vision_handoff_id",
        "generation_requests",
        ["vision_handoff_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Vision evidence must be retained; roll back writers, not evidence tables")
