"""
services/storage_service.py – MinIO S3-compatible object storage service.

All pipeline artifacts (uploaded documents, generated playwright files, etc.)
are stored in MinIO so they survive container restarts and can be shared
across scaled instances.

Bucket layout:
    uploads/{run_id}/{filename}           – original user-uploaded documents
    runs/{run_id}/playwright/{filename}   – generated playwright test artifacts
"""

from __future__ import annotations

import io
import logging
import zipfile
from datetime import timedelta
from typing import Optional

from minio import Minio
from minio.error import S3Error

from app.config import settings

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Singleton client
# ─────────────────────────────────────────────────────────────────────────────

_client: Optional[Minio] = None


def get_minio_client() -> Minio:
    """Return (or lazily create) the module-level MinIO client singleton."""
    global _client
    if _client is None:
        _client = Minio(
            settings.MINIO_ENDPOINT,
            access_key=settings.MINIO_ACCESS_KEY,
            secret_key=settings.MINIO_SECRET_KEY,
            secure=settings.MINIO_USE_SSL,
        )
    return _client


# ─────────────────────────────────────────────────────────────────────────────
# Storage service
# ─────────────────────────────────────────────────────────────────────────────


class StorageService:
    """High-level wrapper around MinIO for pipeline artifact management."""

    def __init__(self) -> None:
        self._client = get_minio_client()
        self._bucket = settings.MINIO_BUCKET

    # ── Bucket helpers ────────────────────────────────────────────────────────

    def ensure_bucket(self) -> None:
        """Create the bucket if it does not already exist."""
        try:
            if not self._client.bucket_exists(self._bucket):
                self._client.make_bucket(self._bucket)
                logger.info("Created MinIO bucket: %s", self._bucket)
        except S3Error as exc:
            logger.error("MinIO bucket check/create failed: %s", exc)
            raise

    # ── Upload ────────────────────────────────────────────────────────────────

    def upload_bytes(
        self, object_name: str, data: bytes, content_type: str = "application/octet-stream"
    ) -> None:
        """Upload raw bytes to *object_name* inside the configured bucket."""
        stream = io.BytesIO(data)
        self._client.put_object(
            self._bucket,
            object_name,
            stream,
            length=len(data),
            content_type=content_type,
        )
        logger.debug("Uploaded %d bytes → %s", len(data), object_name)

    def upload_file_content(
        self,
        run_id: str,
        filename: str,
        content: str,
        subfolder: str = "playwright",
        content_type: str = "text/plain",
    ) -> str:
        """Upload a text artifact generated by a pipeline run.

        Returns the object name (key) inside the bucket.
        """
        object_name = f"runs/{run_id}/{subfolder}/{filename}"
        self.upload_bytes(object_name, content.encode("utf-8"), content_type)
        return object_name

    def upload_document(self, run_id: str, filename: str, data: bytes, content_type: str) -> str:
        """Upload a user-uploaded requirements document.

        Returns the object name (key) inside the bucket.
        """
        object_name = f"uploads/{run_id}/{filename}"
        self.upload_bytes(object_name, data, content_type)
        return object_name

    # ── Download / presigned ──────────────────────────────────────────────────

    def get_presigned_url(self, object_name: str, expires_hours: int = 1) -> str:
        """Return a time-limited presigned GET URL.

        If ``MINIO_PUBLIC_URL`` is configured (e.g. http://localhost:9000),
        the internal hostname is replaced so the URL is browser-accessible.
        """
        url = self._client.presigned_get_object(
            self._bucket,
            object_name,
            expires=timedelta(hours=expires_hours),
        )
        if settings.MINIO_PUBLIC_URL:
            # Replace internal endpoint (e.g. minio:9000) with public URL
            url = url.replace(
                f"http://{settings.MINIO_ENDPOINT}",
                settings.MINIO_PUBLIC_URL.rstrip("/"),
            )
            url = url.replace(
                f"https://{settings.MINIO_ENDPOINT}",
                settings.MINIO_PUBLIC_URL.rstrip("/"),
            )
        return url

    def download_bytes(self, object_name: str) -> bytes:
        """Download an object as raw bytes."""
        response = self._client.get_object(self._bucket, object_name)
        try:
            return response.read()
        finally:
            response.close()
            response.release_conn()

    # ── List ──────────────────────────────────────────────────────────────────

    def list_playwright_files(self, run_id: str) -> list[dict]:
        """List all playwright artifacts for a run.

        Returns a list of ``{"path": str, "size_bytes": int}`` dicts.
        """
        prefix = f"runs/{run_id}/playwright/"
        results = []
        try:
            objects = self._client.list_objects(self._bucket, prefix=prefix, recursive=True)
            for obj in objects:
                results.append(
                    {
                        "path": obj.object_name.removeprefix(prefix),
                        "size_bytes": obj.size or 0,
                    }
                )
        except S3Error as exc:
            logger.warning("Failed to list playwright files for run %s: %s", run_id, exc)
        return results

    # ── ZIP download ──────────────────────────────────────────────────────────

    def build_playwright_zip(self, run_id: str) -> bytes:
        """Build an in-memory ZIP of all playwright artifacts for a run."""
        prefix = f"runs/{run_id}/playwright/"
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            try:
                objects = self._client.list_objects(self._bucket, prefix=prefix, recursive=True)
                for obj in objects:
                    file_data = self.download_bytes(obj.object_name)
                    arcname = obj.object_name.removeprefix(prefix)
                    zf.writestr(arcname, file_data)
            except S3Error as exc:
                logger.warning("Error building zip for run %s: %s", run_id, exc)
        return buf.getvalue()

    def download_playwright_file(self, run_id: str, file_path: str) -> bytes:
        """Download a single playwright artifact by its relative path."""
        object_name = f"runs/{run_id}/playwright/{file_path}"
        return self.download_bytes(object_name)

    # ── Document retrieval ────────────────────────────────────────────────────

    def download_document(self, run_id: str, filename: str) -> bytes:
        """Download the original uploaded document for a run."""
        object_name = f"uploads/{run_id}/{filename}"
        return self.download_bytes(object_name)

    def delete_run_artifacts(self, run_id: str) -> None:
        """Delete all objects for a given run (uploads + generated files)."""
        for prefix in [f"uploads/{run_id}/", f"runs/{run_id}/"]:
            try:
                objects = list(self._client.list_objects(self._bucket, prefix=prefix, recursive=True))
                for obj in objects:
                    self._client.remove_object(self._bucket, obj.object_name)
            except S3Error as exc:
                logger.warning("Error deleting run artifacts %s: %s", run_id, exc)


# Module-level singleton
storage = StorageService()
