"""
tools/test_file_renderer.py
───────────────────────────
Generates runnable unit-test file content and a human-readable Markdown spec
from a list of TestCase dicts (output of TestcaseCrew).

Supported languages / frameworks:
    python      → pytest + httpx
    typescript  → vitest
    javascript  → jest
    java        → JUnit 5 + RestAssured
    go          → stdlib testing + net/http
    csharp      → xUnit + HttpClient

Public API::

    from app.tools.test_file_renderer import (
        group_test_cases,
        render_file,
        render_test_doc_markdown,
        render_fixtures,
    )
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any

# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

_FRAMEWORK_MAP = {
    "python": "pytest",
    "typescript": "vitest",
    "javascript": "jest",
    "java": "junit5",
    "go": "go_test",
    "csharp": "xunit",
}

_EXT_MAP = {
    "python": ".py",
    "typescript": ".test.ts",
    "javascript": ".test.js",
    "java": "Test.java",
    "go": "_test.go",
    "csharp": "Tests.cs",
}


def _snake(text: str) -> str:
    """Convert arbitrary text to snake_case identifier."""
    s = re.sub(r"[^a-zA-Z0-9]+", "_", text.lower()).strip("_")
    return s[:60] or "test"


def _pascal(text: str) -> str:
    """Convert to PascalCase."""
    return "".join(w.capitalize() for w in re.split(r"[^a-zA-Z0-9]+", text) if w)[:60] or "Test"


def _file_stem(endpoint: str, test_type: str) -> str:
    """Derive a short filename stem from an endpoint path."""
    if endpoint and endpoint != "N/A":
        stem = re.sub(r"[^a-zA-Z0-9]+", "_", endpoint.strip("/")).strip("_")
        return (stem or "api")[:40]
    return (_snake(test_type) or "test")[:40]


# ─────────────────────────────────────────────────────────────────────────────
# Grouping
# ─────────────────────────────────────────────────────────────────────────────

def group_test_cases(
    test_cases: list[dict[str, Any]],
) -> dict[str, list[dict[str, Any]]]:
    """
    Group test cases by (api_endpoint or ui_page, test_type) into file buckets.

    Returns:
        ``{ "file_stem": [tc, tc, …] }`` — each bucket becomes one test file.
    """
    buckets: dict[str, list[dict[str, Any]]] = {}
    for tc in test_cases:
        endpoint = tc.get("api_endpoint") or tc.get("ui_page") or "N/A"
        test_type = tc.get("test_type") or "api"
        stem = _file_stem(endpoint, test_type)
        buckets.setdefault(stem, []).append(tc)
    return buckets


# ─────────────────────────────────────────────────────────────────────────────
# Per-language renderers
# ─────────────────────────────────────────────────────────────────────────────

def _render_python(class_name: str, test_cases: list[dict[str, Any]], doc_name: str) -> str:
    req_ids = sorted({tc.get("requirement_id", "") for tc in test_cases if tc.get("requirement_id")})
    lines = [
        f'"""Auto-generated by Auto-AT | Document: {doc_name}',
        f'Covers: {", ".join(req_ids) or "—"}',
        '"""',
        "import os",
        "import pytest",
        "import httpx",
        "",
        'BASE_URL = os.getenv("BASE_URL", "http://localhost:8000")',
        "",
        "",
        f"class Test{_pascal(class_name)}:",
    ]
    for tc in test_cases:
        method = (tc.get("http_method") or "GET").upper()
        endpoint = tc.get("api_endpoint") or "/"
        expected_code = tc.get("expected_status_code") or 200
        body = tc.get("request_body") or {}
        cat = tc.get("category") or "positive"
        title = tc.get("title") or tc.get("id") or "test"
        tc_id = _snake(tc.get("id") or title)
        lines += [
            f"",
            f"    def test_{tc_id}(self):",
            f'        """{title} [{cat}]"""',
            f"        response = httpx.{method.lower()}(",
            f'            f"{{BASE_URL}}{endpoint}",',
        ]
        if body:
            lines.append(f"            json={body!r},")
        lines += [
            f"        )",
            f"        assert response.status_code == {expected_code}",
        ]
        if cat == "positive":
            lines.append("        assert response.json() is not None")
    lines.append("")
    return "\n".join(lines)


def _render_typescript(class_name: str, test_cases: list[dict[str, Any]], doc_name: str) -> str:
    req_ids = sorted({tc.get("requirement_id", "") for tc in test_cases if tc.get("requirement_id")})
    lines = [
        f"// Auto-generated by Auto-AT | Document: {doc_name}",
        f"// Covers: {', '.join(req_ids) or '—'}",
        "import { describe, it, expect } from 'vitest'",
        "",
        f"describe('{_pascal(class_name)}', () => {{",
    ]
    for tc in test_cases:
        method = (tc.get("http_method") or "GET").upper()
        endpoint = tc.get("api_endpoint") or "/"
        expected_code = tc.get("expected_status_code") or 200
        body = tc.get("request_body") or {}
        title = tc.get("title") or tc.get("id") or "test"
        lines += [
            f"",
            f"  it('{title}', async () => {{",
            f"    const res = await fetch(`${{BASE_URL}}{endpoint}`, {{",
            f"      method: '{method}',",
        ]
        if body:
            lines += [
                "      headers: { 'Content-Type': 'application/json' },",
                f"      body: JSON.stringify({body!r}),",
            ]
        lines += [
            "    })",
            f"    expect(res.status).toBe({expected_code})",
            "  })",
        ]
    lines += ["}", ""]
    return "\n".join(lines)


def _render_java(class_name: str, test_cases: list[dict[str, Any]], doc_name: str) -> str:
    req_ids = sorted({tc.get("requirement_id", "") for tc in test_cases if tc.get("requirement_id")})
    pascal = _pascal(class_name)
    lines = [
        f"// Auto-generated by Auto-AT | Document: {doc_name}",
        f"// Covers: {', '.join(req_ids) or '—'}",
        "import io.restassured.RestAssured;",
        "import org.junit.jupiter.api.Test;",
        "import static org.hamcrest.Matchers.*;",
        "",
        f"public class {pascal}Test {{",
    ]
    for tc in test_cases:
        method = (tc.get("http_method") or "GET").lower()
        endpoint = tc.get("api_endpoint") or "/"
        expected_code = tc.get("expected_status_code") or 200
        tc_id = _pascal(tc.get("id") or tc.get("title") or "test")
        lines += [
            "",
            "    @Test",
            f"    public void test{tc_id}() {{",
            f"        RestAssured.{method}(\"{endpoint}\")",
            f"            .then().statusCode({expected_code});",
            "    }",
        ]
    lines += ["}", ""]
    return "\n".join(lines)


def _render_go(class_name: str, test_cases: list[dict[str, Any]], doc_name: str) -> str:
    lines = [
        f"// Auto-generated by Auto-AT | Document: {doc_name}",
        "package tests",
        "",
        "import (",
        '    "net/http"',
        '    "testing"',
        ")",
        "",
    ]
    for tc in test_cases:
        method = (tc.get("http_method") or "GET").upper()
        endpoint = tc.get("api_endpoint") or "/"
        expected_code = tc.get("expected_status_code") or 200
        fn = _pascal(tc.get("id") or tc.get("title") or "test")
        lines += [
            f"func Test{fn}(t *testing.T) {{",
            f'    req, _ := http.NewRequest("{method}", baseURL+"{endpoint}", nil)',
            "    resp, err := http.DefaultClient.Do(req)",
            "    if err != nil { t.Fatal(err) }",
            f"    if resp.StatusCode != {expected_code} {{",
            f'        t.Errorf("expected {expected_code}, got %d", resp.StatusCode)',
            "    }",
            "}",
            "",
        ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Public: render a single file
# ─────────────────────────────────────────────────────────────────────────────

def render_file(
    stem: str,
    test_cases: list[dict[str, Any]],
    language: str,
    doc_name: str,
) -> tuple[str, str]:
    """
    Render a test file for the given language.

    Returns:
        ``(filename, content)`` tuple.
    """
    ext = _EXT_MAP.get(language, ".py")
    filename = f"test_{stem}{ext}" if language in ("python", "typescript", "javascript", "go") else f"{_pascal(stem)}{ext}"
    class_name = stem

    renderers = {
        "python": _render_python,
        "typescript": _render_typescript,
        "javascript": _render_typescript,  # same Jest-compatible syntax
        "java": _render_java,
        "go": _render_go,
        "csharp": _render_java,  # simplified placeholder; same shape as Java
    }
    renderer = renderers.get(language, _render_python)
    content = renderer(class_name, test_cases, doc_name)
    return filename, content


# ─────────────────────────────────────────────────────────────────────────────
# Public: Markdown test case specification
# ─────────────────────────────────────────────────────────────────────────────

def render_test_doc_markdown(
    test_cases: list[dict[str, Any]],
    requirements: list[dict[str, Any]],
    document_name: str,
) -> str:
    """Generate a human-readable Markdown test case specification document."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    req_map = {r.get("id", ""): r for r in requirements}

    # Group TCs by requirement
    by_req: dict[str, list[dict[str, Any]]] = {}
    for tc in test_cases:
        rid = tc.get("requirement_id") or "UNLINKED"
        by_req.setdefault(rid, []).append(tc)

    lines = [
        f"# Test Cases: {document_name}",
        f"",
        f"_Generated by Auto-AT on {now}_",
        f"",
        f"## Summary",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total test cases | {len(test_cases)} |",
        f"| Requirements covered | {len(by_req)} |",
        f"| Requirements in document | {len(requirements)} |",
        f"",
        "---",
        "",
    ]

    for rid, tcs in sorted(by_req.items()):
        req = req_map.get(rid, {})
        req_title = req.get("title") or rid
        req_desc = req.get("description") or ""

        lines += [
            f"## {rid}: {req_title}",
            "",
        ]
        if req_desc:
            lines += [f"> {req_desc}", ""]

        # Summary table
        lines += [
            "| TC ID | Title | Type | Category | Priority | Expected Status |",
            "|-------|-------|------|----------|----------|-----------------|",
        ]
        for tc in tcs:
            tc_id = tc.get("id") or "—"
            tc_title = tc.get("title") or "—"
            tc_type = tc.get("test_type") or "api"
            tc_cat = tc.get("category") or "positive"
            tc_prio = tc.get("priority") or "medium"
            tc_code = tc.get("expected_status_code") or "—"
            lines.append(f"| {tc_id} | {tc_title} | {tc_type} | {tc_cat} | {tc_prio} | {tc_code} |")

        lines.append("")

        # Detailed cards
        for tc in tcs:
            tc_id = tc.get("id") or "—"
            tc_title = tc.get("title") or "—"
            pre = tc.get("preconditions") or "—"
            expected = tc.get("expected_result") or "—"
            steps: list[dict] = tc.get("steps") or []
            endpoint = tc.get("api_endpoint") or ""
            method = tc.get("http_method") or ""

            lines += [f"### {tc_id}: {tc_title}", ""]
            if endpoint:
                lines += [f"**Endpoint:** `{method} {endpoint}`", ""]
            lines += [f"**Precondition:** {pre}", "", "**Steps:**", ""]
            for i, step in enumerate(steps, 1):
                action = step.get("action") or str(step)
                exp_step = step.get("expected_result") or ""
                lines.append(f"{i}. {action}")
                if exp_step:
                    lines.append(f"   - *Expected:* {exp_step}")
            if not steps:
                lines.append("_(no steps defined)_")
            lines += ["", f"**Overall expected result:** {expected}", "", "---", ""]

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Public: test data fixtures
# ─────────────────────────────────────────────────────────────────────────────

def render_fixtures(test_cases: list[dict[str, Any]]) -> dict[str, Any]:
    """Extract and organise test data fixtures from the test cases."""
    fixtures: dict[str, Any] = {}
    for tc in test_cases:
        tc_id = tc.get("id") or "unknown"
        body = tc.get("request_body")
        headers = tc.get("request_headers")
        if body or headers:
            fixtures[tc_id] = {}
            if body:
                fixtures[tc_id]["request_body"] = body
            if headers:
                fixtures[tc_id]["headers"] = headers
    return fixtures
