"""Generate worker types and validation schemas from the authoritative Python models.

Run from auto-at-ui: uv run python packages/contracts/export_vision_worker.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "src"))

from auto_at.contracts import vision, vision_worker  # noqa: E402

MODELS = [
    vision.VisualLocatorDescriptor,
    vision.VisualLocatorEvidence,
    vision.VisualOperation,
    vision.VisualOperationFrame,
    vision.VisualCheckpoint,
    vision.VisualLocatorHandoff,
    vision.VisualWorkerCommand,
    vision_worker.VisualWorkerIdentity,
    vision_worker.VisualWorkerOpen,
    vision_worker.VisualWorkerPrepare,
    vision_worker.VisualWorkerExecute,
    vision_worker.VisualWorkerAck,
    vision_worker.VisualWorkerOperationResult,
]


def ts_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    kind = schema.get("type")
    if kind == "object":
        required = schema.get("required", [])
        return (
            "{ "
            + "; ".join(
                f"{name}{'' if name in required or 'default' in child else '?'}: {ts_type(child)}"
                for name, child in schema.get("properties", {}).items()
            )
            + " }"
        )
    if kind == "array":
        return f"Array<{ts_type(schema['items'])}>"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "null": "null",
        "boolean": "boolean",
    }.get(kind, "unknown")


def render() -> str:
    definitions = {}
    for model in MODELS:
        schema = model.model_json_schema()
        definitions.update(schema.pop("$defs", {}))
        definitions[model.__name__] = schema
    types = "\n".join(
        f"export type {name} = {ts_type(schema)};" for name, schema in sorted(definitions.items())
    )
    return (
        "// Generated by packages/contracts/export_vision_worker.py; do not edit.\n"
        + types
        + "\nexport const visionSchemas: Record<string, unknown> = "
        + json.dumps(definitions, ensure_ascii=False, indent=2)
        + ";\n"
    )


if __name__ == "__main__":
    target = Path(__file__).parents[2] / "workers/playwright/src/vision-contract.generated.ts"
    generated = render()
    if "--check" in sys.argv:
        if target.read_text(encoding="utf-8") != generated:
            raise SystemExit("Vision worker contracts require regeneration")
    else:
        target.write_text(generated, encoding="utf-8")
