"use client";

import { useEffect, useState } from "react";
import { PageHeader } from "../components/page-header";
import { EmptyState, ErrorState, LoadingState } from "../components/states";

type User = { id: string; email: string; role: string; enabled: boolean; force_password_change: boolean };
const apiUrl = process.env.NEXT_PUBLIC_CONTROL_PLANE_URL ?? "http://localhost:7000";
const csrf = () => document.cookie.split("; ").find((cookie) => cookie.startsWith("auto_at_csrf="))?.split("=")[1] ?? "";

export default function AdminPage() {
  const [users, setUsers] = useState<User[] | null>(null); const [error, setError] = useState(""); const [email, setEmail] = useState(""); const [role, setRole] = useState("contributor"); const [temporaryPassword, setTemporaryPassword] = useState<string | null>(null);
  const load = async () => { const response = await fetch(`${apiUrl}/api/v1/admin/users`, { credentials: "include" }); if (!response.ok) { setError("User administration is unavailable for this account."); return; } setUsers(await response.json()); };
  useEffect(() => { void load(); }, []);
  const provision = async (e: React.FormEvent) => { e.preventDefault(); setError(""); const response = await fetch(`${apiUrl}/api/v1/admin/users`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf() }, body: JSON.stringify({ email, role }) }); if (!response.ok) { setError("The account could not be provisioned."); return; } const user = await response.json(); setTemporaryPassword(user.temporary_password); setEmail(""); await load(); };
  const disable = async (id: string) => { await fetch(`${apiUrl}/api/v1/admin/users/${id}`, { method: "DELETE", credentials: "include", headers: { "X-CSRF-Token": csrf() } }); await load(); };
  return <><PageHeader eyebrow="Administration" title="Users" description="Provision tenant accounts and assign least-privilege roles." />{temporaryPassword && <section className="notice" role="status"><strong>Copy this temporary password now:</strong><code>{temporaryPassword}</code><button type="button" className="button button--secondary" onClick={() => setTemporaryPassword(null)}>I have copied it</button><p>It will not be shown again after this acknowledgement, navigation, or reload.</p></section>}<section className="panel"><h2>Provision user</h2><form className="form-grid" onSubmit={(e) => void provision(e)}><label className="field">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label className="field">Role<select value={role} onChange={(e) => setRole(e.target.value)}><option value="viewer">Viewer</option><option value="contributor">Contributor</option><option value="reviewer">Reviewer</option><option value="project_admin">Project admin</option><option value="tenant_admin">Tenant admin</option></select></label><div className="form-actions"><button className="button">Provision account</button></div></form></section>{error && <ErrorState title="Unable to load users">{error}</ErrorState>}{users === null && !error && <LoadingState title="Loading users" />}{users?.length === 0 && <EmptyState title="No tenant users">Provision the first collaborator above.</EmptyState>}{users && users.length > 0 && <section className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th /></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td>{user.email}{user.force_password_change && <small> · password change required</small>}</td><td>{user.role}</td><td>{user.enabled ? "Active" : "Disabled"}</td><td>{user.enabled && <button className="button button--secondary" type="button" onClick={() => void disable(user.id)}>Disable</button>}</td></tr>)}</tbody></table></section>}</>;
}
