[SERVICE]
    Flush        1
    Log_Level    info
    storage.path /buffers
    storage.sync normal
    storage.checksum on
    storage.max_chunks_up 64

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*-json.log
    Parser            docker
    Tag               docker.*
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    storage.type      filesystem

[FILTER]
    Name          parser
    Match         docker.*
    Key_Name      log
    Parser        first_party_json
    Reserve_Data  Off

[FILTER]
    Name    lua
    Match   docker.*
    script  /fluent-bit/etc/redact.lua
    call    redact

[OUTPUT]
    Name          loki
    Match         docker.*
    Host          loki
    Port          3100
    Labels        service=$service,environment=$environment,level=$level
    remove_keys    timestamp,service,environment,level
    line_format    json
    Retry_Limit   10
