// Generated by packages/contracts/export_vision_worker.py; do not edit.
export type VisualBoundingBox = { x: number; y: number; width: number; height: number };
export type VisualCheckpoint = { id: string; state_id: string; ancestor_operation_ids: Array<string>; url_fingerprint: string; semantic_fingerprint: string; scroll_x: number; scroll_y: number; form_presence_fingerprint: string | null };
export type VisualHandoffBranch = { id: string; steps: Array<VisualHandoffStep>; status: "ready" | "blocked"; reason_code: string | null };
export type VisualHandoffStep = { operation_id: string; locator_id: string | null; input_reference: string | null; observation_codes: Array<string> };
export type VisualLocatorDescriptor = { schema_version: "v1"; strategy: "role" | "label" | "test_id" | "css"; value: string; role: string | null; exact: true; scope: Array<VisualLocatorScope> };
export type VisualLocatorEvidence = { schema_version: "v1"; id: string; tenant_id: string; project_id: string; session_id: string; operation_id: string; state_id: string; proposal_id: string; originating_frame_id: string; descriptor: VisualLocatorDescriptor | null; bounding_box: VisualBoundingBox | null; matched_count: number; target_match: boolean; actionable: boolean; model_confidence: number; verified_at: string | null; status: "verified" | "ambiguous" | "not_found" | "stale" | "unsupported" | "redacted"; reason_code: string | null };
export type VisualLocatorHandoff = { schema_version: "v1"; id: string; tenant_id: string; project_id: string; session_id: string; version: number; branches: Array<VisualHandoffBranch>; unresolved_count: number; created_at: string; content_hash: string };
export type VisualLocatorScope = { kind: "iframe" | "shadow"; selector: string };
export type VisualOperation = { schema_version: "v1"; id: string; tenant_id: string; project_id: string; session_id: string; sequence: number; attempt: number; parent_operation_id: string | null; checkpoint_id: string | null; edge_id: string | null; state_id: string | null; proposal_id: string | null; purpose: "explore" | "restore" | "replay" | "setup"; action_kind: "click" | "type" | "scroll" | "wait" | "navigate" | "back" | "close_popup"; locator_id: string | null; expected_parent_fingerprint: string | null; started_at: string; ended_at: string | null; status: "prepared" | "executing" | "completed" | "failed" | "unknown" | "rejected"; outcome_code: string | null; actual_before_frame_id: string | null; actual_after_frame_id: string | null; before_unavailable_reason: string | null; after_unavailable_reason: string | null; before_page_id: string | null; after_page_id: string | null; url_change: "unchanged" | "changed" | "unavailable"; visual_change: "unchanged" | "changed" | "unavailable" };
export type VisualOperationFrame = { schema_version: "v1"; id: string; tenant_id: string; project_id: string; session_id: string; operation_id: string; role: "before" | "after"; checksum: string; byte_count: number; content_type: "image/png" | "image/jpeg"; captured_at: string; deleted_at: string | null };
export type VisualWorkerAck = { contract_version: "v4"; tenant_id: string; project_id: string; session_id: string; fencing_token: number; operation_id: string; persisted_frame_ids: Array<string> };
export type VisualWorkerAction = { kind: "click" | "type" | "scroll" | "wait" | "navigate" | "back" | "close_popup"; x: number | null; y: number | null; text: string | null; delta_y: number | null; duration_ms: number | null };
export type VisualWorkerCommand = { contract_version: "v4"; tenant_id: string; project_id: string; session_id: string; fencing_token: number; operation_id: string; command: "prepare" | "execute" | "observe" | "restore" | "close"; deadline: string };
export type VisualWorkerExecute = { contract_version: "v4"; tenant_id: string; project_id: string; session_id: string; fencing_token: number; operation_id: string; prepared_handle: string; before_frame_id: string; before_checksum: string; before_persisted: true };
export type VisualWorkerIdentity = { contract_version: "v4"; tenant_id: string; project_id: string; session_id: string; fencing_token: number };
export type VisualWorkerOpen = { contract_version: "v4"; tenant_id: string; project_id: string; session_id: string; fencing_token: number; target_url: string; allowed_origins: Array<string>; deadline: string; max_session_seconds: number; max_states: number; max_hops: number; max_screenshot_bytes: number };
export type VisualWorkerOperationResult = { operation: VisualOperation; frames: Array<VisualOperationFrame>; locator: VisualLocatorEvidence | null; prepared_handle: string; state_fingerprint: string | null; checkpoint: VisualCheckpoint | null; semantic_change: "changed" | "unchanged" | "unavailable"; duration_ms: number; acknowledged: boolean; replayable: boolean };
export type VisualWorkerPrepare = { contract_version: "v4"; tenant_id: string; project_id: string; session_id: string; fencing_token: number; operation_id: string; purpose: "explore" | "restore" | "replay" | "setup"; action: VisualWorkerAction; expected_state_fingerprint: string; state_id: string | null; proposal_id: string | null; model_confidence: number; checkpoint_id: string | null; checkpoint_state_id: string | null; restore_checkpoint_id: string | null; replay_operation_id: string | null; expected_locator: VisualLocatorDescriptor | null };
export const visionSchemas: Record<string, unknown> = {
  "VisualLocatorScope": {
    "additionalProperties": false,
    "properties": {
      "kind": {
        "enum": [
          "iframe",
          "shadow"
        ],
        "title": "Kind",
        "type": "string"
      },
      "selector": {
        "maxLength": 240,
        "minLength": 1,
        "title": "Selector",
        "type": "string"
      }
    },
    "required": [
      "kind",
      "selector"
    ],
    "title": "VisualLocatorScope",
    "type": "object"
  },
  "VisualLocatorDescriptor": {
    "additionalProperties": false,
    "properties": {
      "schema_version": {
        "const": "v1",
        "default": "v1",
        "title": "Schema Version",
        "type": "string"
      },
      "strategy": {
        "enum": [
          "role",
          "label",
          "test_id",
          "css"
        ],
        "title": "Strategy",
        "type": "string"
      },
      "value": {
        "maxLength": 240,
        "minLength": 1,
        "title": "Value",
        "type": "string"
      },
      "role": {
        "anyOf": [
          {
            "pattern": "^[a-z]{3,32}$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Role"
      },
      "exact": {
        "const": true,
        "default": true,
        "title": "Exact",
        "type": "boolean"
      },
      "scope": {
        "default": [],
        "items": {
          "$ref": "#/$defs/VisualLocatorScope"
        },
        "maxItems": 8,
        "title": "Scope",
        "type": "array"
      }
    },
    "required": [
      "strategy",
      "value"
    ],
    "title": "VisualLocatorDescriptor",
    "type": "object"
  },
  "VisualBoundingBox": {
    "additionalProperties": false,
    "properties": {
      "x": {
        "maximum": 1,
        "minimum": 0,
        "title": "X",
        "type": "number"
      },
      "y": {
        "maximum": 1,
        "minimum": 0,
        "title": "Y",
        "type": "number"
      },
      "width": {
        "exclusiveMinimum": 0,
        "maximum": 1,
        "title": "Width",
        "type": "number"
      },
      "height": {
        "exclusiveMinimum": 0,
        "maximum": 1,
        "title": "Height",
        "type": "number"
      }
    },
    "required": [
      "x",
      "y",
      "width",
      "height"
    ],
    "title": "VisualBoundingBox",
    "type": "object"
  },
  "VisualLocatorEvidence": {
    "additionalProperties": false,
    "properties": {
      "schema_version": {
        "const": "v1",
        "default": "v1",
        "title": "Schema Version",
        "type": "string"
      },
      "id": {
        "format": "uuid",
        "title": "Id",
        "type": "string"
      },
      "tenant_id": {
        "maxLength": 200,
        "minLength": 1,
        "title": "Tenant Id",
        "type": "string"
      },
      "project_id": {
        "format": "uuid",
        "title": "Project Id",
        "type": "string"
      },
      "session_id": {
        "format": "uuid",
        "title": "Session Id",
        "type": "string"
      },
      "operation_id": {
        "format": "uuid",
        "title": "Operation Id",
        "type": "string"
      },
      "state_id": {
        "format": "uuid",
        "title": "State Id",
        "type": "string"
      },
      "proposal_id": {
        "format": "uuid",
        "title": "Proposal Id",
        "type": "string"
      },
      "originating_frame_id": {
        "format": "uuid",
        "title": "Originating Frame Id",
        "type": "string"
      },
      "descriptor": {
        "anyOf": [
          {
            "$ref": "#/$defs/VisualLocatorDescriptor"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "bounding_box": {
        "anyOf": [
          {
            "$ref": "#/$defs/VisualBoundingBox"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "matched_count": {
        "maximum": 100000,
        "minimum": 0,
        "title": "Matched Count",
        "type": "integer"
      },
      "target_match": {
        "default": false,
        "title": "Target Match",
        "type": "boolean"
      },
      "actionable": {
        "default": false,
        "title": "Actionable",
        "type": "boolean"
      },
      "model_confidence": {
        "maximum": 1,
        "minimum": 0,
        "title": "Model Confidence",
        "type": "number"
      },
      "verified_at": {
        "anyOf": [
          {
            "format": "date-time",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Verified At"
      },
      "status": {
        "enum": [
          "verified",
          "ambiguous",
          "not_found",
          "stale",
          "unsupported",
          "redacted"
        ],
        "title": "Status",
        "type": "string"
      },
      "reason_code": {
        "anyOf": [
          {
            "pattern": "^[a-z][a-z0-9_]{0,79}$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Reason Code"
      }
    },
    "required": [
      "id",
      "tenant_id",
      "project_id",
      "session_id",
      "operation_id",
      "state_id",
      "proposal_id",
      "originating_frame_id",
      "matched_count",
      "model_confidence",
      "status"
    ],
    "title": "VisualLocatorEvidence",
    "type": "object"
  },
  "VisualOperation": {
    "additionalProperties": false,
    "properties": {
      "schema_version": {
        "const": "v1",
        "default": "v1",
        "title": "Schema Version",
        "type": "string"
      },
      "id": {
        "format": "uuid",
        "title": "Id",
        "type": "string"
      },
      "tenant_id": {
        "maxLength": 200,
        "minLength": 1,
        "title": "Tenant Id",
        "type": "string"
      },
      "project_id": {
        "format": "uuid",
        "title": "Project Id",
        "type": "string"
      },
      "session_id": {
        "format": "uuid",
        "title": "Session Id",
        "type": "string"
      },
      "sequence": {
        "maximum": 100000,
        "minimum": 1,
        "title": "Sequence",
        "type": "integer"
      },
      "attempt": {
        "default": 1,
        "maximum": 100,
        "minimum": 1,
        "title": "Attempt",
        "type": "integer"
      },
      "parent_operation_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Parent Operation Id"
      },
      "checkpoint_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Checkpoint Id"
      },
      "edge_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Edge Id"
      },
      "state_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "State Id"
      },
      "proposal_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Proposal Id"
      },
      "purpose": {
        "enum": [
          "explore",
          "restore",
          "replay",
          "setup"
        ],
        "title": "Purpose",
        "type": "string"
      },
      "action_kind": {
        "enum": [
          "click",
          "type",
          "scroll",
          "wait",
          "navigate",
          "back",
          "close_popup"
        ],
        "title": "Action Kind",
        "type": "string"
      },
      "locator_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Locator Id"
      },
      "expected_parent_fingerprint": {
        "anyOf": [
          {
            "pattern": "^[a-f0-9]{64}$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Expected Parent Fingerprint"
      },
      "started_at": {
        "format": "date-time",
        "title": "Started At",
        "type": "string"
      },
      "ended_at": {
        "anyOf": [
          {
            "format": "date-time",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Ended At"
      },
      "status": {
        "enum": [
          "prepared",
          "executing",
          "completed",
          "failed",
          "unknown",
          "rejected"
        ],
        "title": "Status",
        "type": "string"
      },
      "outcome_code": {
        "anyOf": [
          {
            "pattern": "^[a-z][a-z0-9_]{0,79}$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Outcome Code"
      },
      "actual_before_frame_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Actual Before Frame Id"
      },
      "actual_after_frame_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Actual After Frame Id"
      },
      "before_unavailable_reason": {
        "anyOf": [
          {
            "pattern": "^[a-z][a-z0-9_]{0,79}$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Before Unavailable Reason"
      },
      "after_unavailable_reason": {
        "anyOf": [
          {
            "pattern": "^[a-z][a-z0-9_]{0,79}$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "After Unavailable Reason"
      },
      "before_page_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Before Page Id"
      },
      "after_page_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "After Page Id"
      },
      "url_change": {
        "default": "unavailable",
        "enum": [
          "unchanged",
          "changed",
          "unavailable"
        ],
        "title": "Url Change",
        "type": "string"
      },
      "visual_change": {
        "default": "unavailable",
        "enum": [
          "unchanged",
          "changed",
          "unavailable"
        ],
        "title": "Visual Change",
        "type": "string"
      }
    },
    "required": [
      "id",
      "tenant_id",
      "project_id",
      "session_id",
      "sequence",
      "purpose",
      "action_kind",
      "started_at",
      "status"
    ],
    "title": "VisualOperation",
    "type": "object"
  },
  "VisualOperationFrame": {
    "additionalProperties": false,
    "properties": {
      "schema_version": {
        "const": "v1",
        "default": "v1",
        "title": "Schema Version",
        "type": "string"
      },
      "id": {
        "format": "uuid",
        "title": "Id",
        "type": "string"
      },
      "tenant_id": {
        "maxLength": 200,
        "minLength": 1,
        "title": "Tenant Id",
        "type": "string"
      },
      "project_id": {
        "format": "uuid",
        "title": "Project Id",
        "type": "string"
      },
      "session_id": {
        "format": "uuid",
        "title": "Session Id",
        "type": "string"
      },
      "operation_id": {
        "format": "uuid",
        "title": "Operation Id",
        "type": "string"
      },
      "role": {
        "enum": [
          "before",
          "after"
        ],
        "title": "Role",
        "type": "string"
      },
      "checksum": {
        "pattern": "^[a-f0-9]{64}$",
        "title": "Checksum",
        "type": "string"
      },
      "byte_count": {
        "maximum": 5000000,
        "minimum": 1,
        "title": "Byte Count",
        "type": "integer"
      },
      "content_type": {
        "enum": [
          "image/png",
          "image/jpeg"
        ],
        "title": "Content Type",
        "type": "string"
      },
      "captured_at": {
        "format": "date-time",
        "title": "Captured At",
        "type": "string"
      },
      "deleted_at": {
        "anyOf": [
          {
            "format": "date-time",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Deleted At"
      }
    },
    "required": [
      "id",
      "tenant_id",
      "project_id",
      "session_id",
      "operation_id",
      "role",
      "checksum",
      "byte_count",
      "content_type",
      "captured_at"
    ],
    "title": "VisualOperationFrame",
    "type": "object"
  },
  "VisualCheckpoint": {
    "additionalProperties": false,
    "description": "Safe invariants only. Browser heap, form values and storage remain in worker RAM.",
    "properties": {
      "id": {
        "format": "uuid",
        "title": "Id",
        "type": "string"
      },
      "state_id": {
        "format": "uuid",
        "title": "State Id",
        "type": "string"
      },
      "ancestor_operation_ids": {
        "default": [],
        "items": {
          "format": "uuid",
          "type": "string"
        },
        "maxItems": 100,
        "title": "Ancestor Operation Ids",
        "type": "array"
      },
      "url_fingerprint": {
        "pattern": "^[a-f0-9]{64}$",
        "title": "Url Fingerprint",
        "type": "string"
      },
      "semantic_fingerprint": {
        "pattern": "^[a-f0-9]{64}$",
        "title": "Semantic Fingerprint",
        "type": "string"
      },
      "scroll_x": {
        "maximum": 10000000,
        "minimum": 0,
        "title": "Scroll X",
        "type": "integer"
      },
      "scroll_y": {
        "maximum": 10000000,
        "minimum": 0,
        "title": "Scroll Y",
        "type": "integer"
      },
      "form_presence_fingerprint": {
        "anyOf": [
          {
            "pattern": "^[a-f0-9]{64}$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Form Presence Fingerprint"
      }
    },
    "required": [
      "id",
      "state_id",
      "url_fingerprint",
      "semantic_fingerprint",
      "scroll_x",
      "scroll_y"
    ],
    "title": "VisualCheckpoint",
    "type": "object"
  },
  "VisualHandoffBranch": {
    "additionalProperties": false,
    "properties": {
      "id": {
        "format": "uuid",
        "title": "Id",
        "type": "string"
      },
      "steps": {
        "items": {
          "$ref": "#/$defs/VisualHandoffStep"
        },
        "maxItems": 100,
        "minItems": 1,
        "title": "Steps",
        "type": "array"
      },
      "status": {
        "enum": [
          "ready",
          "blocked"
        ],
        "title": "Status",
        "type": "string"
      },
      "reason_code": {
        "anyOf": [
          {
            "pattern": "^[a-z][a-z0-9_]{0,79}$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Reason Code"
      }
    },
    "required": [
      "id",
      "steps",
      "status"
    ],
    "title": "VisualHandoffBranch",
    "type": "object"
  },
  "VisualHandoffStep": {
    "additionalProperties": false,
    "properties": {
      "operation_id": {
        "format": "uuid",
        "title": "Operation Id",
        "type": "string"
      },
      "locator_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Locator Id"
      },
      "input_reference": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Input Reference"
      },
      "observation_codes": {
        "default": [],
        "items": {
          "pattern": "^[a-z][a-z0-9_]{0,79}$",
          "type": "string"
        },
        "maxItems": 20,
        "title": "Observation Codes",
        "type": "array"
      }
    },
    "required": [
      "operation_id"
    ],
    "title": "VisualHandoffStep",
    "type": "object"
  },
  "VisualLocatorHandoff": {
    "additionalProperties": false,
    "properties": {
      "schema_version": {
        "const": "v1",
        "default": "v1",
        "title": "Schema Version",
        "type": "string"
      },
      "id": {
        "format": "uuid",
        "title": "Id",
        "type": "string"
      },
      "tenant_id": {
        "maxLength": 200,
        "minLength": 1,
        "title": "Tenant Id",
        "type": "string"
      },
      "project_id": {
        "format": "uuid",
        "title": "Project Id",
        "type": "string"
      },
      "session_id": {
        "format": "uuid",
        "title": "Session Id",
        "type": "string"
      },
      "version": {
        "maximum": 100,
        "minimum": 1,
        "title": "Version",
        "type": "integer"
      },
      "branches": {
        "default": [],
        "items": {
          "$ref": "#/$defs/VisualHandoffBranch"
        },
        "maxItems": 50,
        "title": "Branches",
        "type": "array"
      },
      "unresolved_count": {
        "maximum": 100000,
        "minimum": 0,
        "title": "Unresolved Count",
        "type": "integer"
      },
      "created_at": {
        "format": "date-time",
        "title": "Created At",
        "type": "string"
      },
      "content_hash": {
        "pattern": "^[a-f0-9]{64}$",
        "title": "Content Hash",
        "type": "string"
      }
    },
    "required": [
      "id",
      "tenant_id",
      "project_id",
      "session_id",
      "version",
      "unresolved_count",
      "created_at",
      "content_hash"
    ],
    "title": "VisualLocatorHandoff",
    "type": "object"
  },
  "VisualWorkerCommand": {
    "additionalProperties": false,
    "description": "v4 control message, independent of the deterministic execution v1 envelope.",
    "properties": {
      "contract_version": {
        "const": "v4",
        "default": "v4",
        "title": "Contract Version",
        "type": "string"
      },
      "tenant_id": {
        "maxLength": 200,
        "minLength": 1,
        "title": "Tenant Id",
        "type": "string"
      },
      "project_id": {
        "format": "uuid",
        "title": "Project Id",
        "type": "string"
      },
      "session_id": {
        "format": "uuid",
        "title": "Session Id",
        "type": "string"
      },
      "fencing_token": {
        "minimum": 1,
        "title": "Fencing Token",
        "type": "integer"
      },
      "operation_id": {
        "format": "uuid",
        "title": "Operation Id",
        "type": "string"
      },
      "command": {
        "enum": [
          "prepare",
          "execute",
          "observe",
          "restore",
          "close"
        ],
        "title": "Command",
        "type": "string"
      },
      "deadline": {
        "format": "date-time",
        "title": "Deadline",
        "type": "string"
      }
    },
    "required": [
      "tenant_id",
      "project_id",
      "session_id",
      "fencing_token",
      "operation_id",
      "command",
      "deadline"
    ],
    "title": "VisualWorkerCommand",
    "type": "object"
  },
  "VisualWorkerIdentity": {
    "additionalProperties": false,
    "properties": {
      "contract_version": {
        "const": "v4",
        "default": "v4",
        "title": "Contract Version",
        "type": "string"
      },
      "tenant_id": {
        "maxLength": 200,
        "minLength": 1,
        "title": "Tenant Id",
        "type": "string"
      },
      "project_id": {
        "format": "uuid",
        "title": "Project Id",
        "type": "string"
      },
      "session_id": {
        "format": "uuid",
        "title": "Session Id",
        "type": "string"
      },
      "fencing_token": {
        "maximum": 9007199254740991,
        "minimum": 1,
        "title": "Fencing Token",
        "type": "integer"
      }
    },
    "required": [
      "tenant_id",
      "project_id",
      "session_id",
      "fencing_token"
    ],
    "title": "VisualWorkerIdentity",
    "type": "object"
  },
  "VisualWorkerOpen": {
    "additionalProperties": false,
    "properties": {
      "contract_version": {
        "const": "v4",
        "default": "v4",
        "title": "Contract Version",
        "type": "string"
      },
      "tenant_id": {
        "maxLength": 200,
        "minLength": 1,
        "title": "Tenant Id",
        "type": "string"
      },
      "project_id": {
        "format": "uuid",
        "title": "Project Id",
        "type": "string"
      },
      "session_id": {
        "format": "uuid",
        "title": "Session Id",
        "type": "string"
      },
      "fencing_token": {
        "maximum": 9007199254740991,
        "minimum": 1,
        "title": "Fencing Token",
        "type": "integer"
      },
      "target_url": {
        "maxLength": 2000,
        "minLength": 1,
        "title": "Target Url",
        "type": "string"
      },
      "allowed_origins": {
        "items": {
          "type": "string"
        },
        "maxItems": 100,
        "minItems": 1,
        "title": "Allowed Origins",
        "type": "array"
      },
      "deadline": {
        "format": "date-time",
        "title": "Deadline",
        "type": "string"
      },
      "max_session_seconds": {
        "maximum": 3600,
        "minimum": 1,
        "title": "Max Session Seconds",
        "type": "integer"
      },
      "max_states": {
        "maximum": 200,
        "minimum": 1,
        "title": "Max States",
        "type": "integer"
      },
      "max_hops": {
        "maximum": 10,
        "minimum": 1,
        "title": "Max Hops",
        "type": "integer"
      },
      "max_screenshot_bytes": {
        "maximum": 5000000,
        "minimum": 1024,
        "title": "Max Screenshot Bytes",
        "type": "integer"
      }
    },
    "required": [
      "tenant_id",
      "project_id",
      "session_id",
      "fencing_token",
      "target_url",
      "allowed_origins",
      "deadline",
      "max_session_seconds",
      "max_states",
      "max_hops",
      "max_screenshot_bytes"
    ],
    "title": "VisualWorkerOpen",
    "type": "object"
  },
  "VisualWorkerAction": {
    "additionalProperties": false,
    "properties": {
      "kind": {
        "enum": [
          "click",
          "type",
          "scroll",
          "wait",
          "navigate",
          "back",
          "close_popup"
        ],
        "title": "Kind",
        "type": "string"
      },
      "x": {
        "anyOf": [
          {
            "maximum": 1,
            "minimum": 0,
            "type": "number"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "X"
      },
      "y": {
        "anyOf": [
          {
            "maximum": 1,
            "minimum": 0,
            "type": "number"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Y"
      },
      "text": {
        "anyOf": [
          {
            "maxLength": 1000,
            "minLength": 1,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Text"
      },
      "delta_y": {
        "anyOf": [
          {
            "maximum": 2000,
            "minimum": -2000,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Delta Y"
      },
      "duration_ms": {
        "anyOf": [
          {
            "maximum": 10000,
            "minimum": 100,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Duration Ms"
      }
    },
    "required": [
      "kind"
    ],
    "title": "VisualWorkerAction",
    "type": "object"
  },
  "VisualWorkerPrepare": {
    "additionalProperties": false,
    "properties": {
      "contract_version": {
        "const": "v4",
        "default": "v4",
        "title": "Contract Version",
        "type": "string"
      },
      "tenant_id": {
        "maxLength": 200,
        "minLength": 1,
        "title": "Tenant Id",
        "type": "string"
      },
      "project_id": {
        "format": "uuid",
        "title": "Project Id",
        "type": "string"
      },
      "session_id": {
        "format": "uuid",
        "title": "Session Id",
        "type": "string"
      },
      "fencing_token": {
        "maximum": 9007199254740991,
        "minimum": 1,
        "title": "Fencing Token",
        "type": "integer"
      },
      "operation_id": {
        "format": "uuid",
        "title": "Operation Id",
        "type": "string"
      },
      "purpose": {
        "enum": [
          "explore",
          "restore",
          "replay",
          "setup"
        ],
        "title": "Purpose",
        "type": "string"
      },
      "action": {
        "$ref": "#/$defs/VisualWorkerAction"
      },
      "expected_state_fingerprint": {
        "pattern": "^[a-f0-9]{64}$",
        "title": "Expected State Fingerprint",
        "type": "string"
      },
      "state_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "State Id"
      },
      "proposal_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Proposal Id"
      },
      "model_confidence": {
        "default": 0,
        "maximum": 1,
        "minimum": 0,
        "title": "Model Confidence",
        "type": "number"
      },
      "checkpoint_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Checkpoint Id"
      },
      "checkpoint_state_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Checkpoint State Id"
      },
      "restore_checkpoint_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Restore Checkpoint Id"
      },
      "replay_operation_id": {
        "anyOf": [
          {
            "format": "uuid",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Replay Operation Id"
      },
      "expected_locator": {
        "anyOf": [
          {
            "$ref": "#/$defs/VisualLocatorDescriptor"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      }
    },
    "required": [
      "tenant_id",
      "project_id",
      "session_id",
      "fencing_token",
      "operation_id",
      "purpose",
      "action",
      "expected_state_fingerprint"
    ],
    "title": "VisualWorkerPrepare",
    "type": "object"
  },
  "VisualWorkerExecute": {
    "additionalProperties": false,
    "properties": {
      "contract_version": {
        "const": "v4",
        "default": "v4",
        "title": "Contract Version",
        "type": "string"
      },
      "tenant_id": {
        "maxLength": 200,
        "minLength": 1,
        "title": "Tenant Id",
        "type": "string"
      },
      "project_id": {
        "format": "uuid",
        "title": "Project Id",
        "type": "string"
      },
      "session_id": {
        "format": "uuid",
        "title": "Session Id",
        "type": "string"
      },
      "fencing_token": {
        "maximum": 9007199254740991,
        "minimum": 1,
        "title": "Fencing Token",
        "type": "integer"
      },
      "operation_id": {
        "format": "uuid",
        "title": "Operation Id",
        "type": "string"
      },
      "prepared_handle": {
        "format": "uuid",
        "title": "Prepared Handle",
        "type": "string"
      },
      "before_frame_id": {
        "format": "uuid",
        "title": "Before Frame Id",
        "type": "string"
      },
      "before_checksum": {
        "pattern": "^[a-f0-9]{64}$",
        "title": "Before Checksum",
        "type": "string"
      },
      "before_persisted": {
        "const": true,
        "title": "Before Persisted",
        "type": "boolean"
      }
    },
    "required": [
      "tenant_id",
      "project_id",
      "session_id",
      "fencing_token",
      "operation_id",
      "prepared_handle",
      "before_frame_id",
      "before_checksum",
      "before_persisted"
    ],
    "title": "VisualWorkerExecute",
    "type": "object"
  },
  "VisualWorkerAck": {
    "additionalProperties": false,
    "properties": {
      "contract_version": {
        "const": "v4",
        "default": "v4",
        "title": "Contract Version",
        "type": "string"
      },
      "tenant_id": {
        "maxLength": 200,
        "minLength": 1,
        "title": "Tenant Id",
        "type": "string"
      },
      "project_id": {
        "format": "uuid",
        "title": "Project Id",
        "type": "string"
      },
      "session_id": {
        "format": "uuid",
        "title": "Session Id",
        "type": "string"
      },
      "fencing_token": {
        "maximum": 9007199254740991,
        "minimum": 1,
        "title": "Fencing Token",
        "type": "integer"
      },
      "operation_id": {
        "format": "uuid",
        "title": "Operation Id",
        "type": "string"
      },
      "persisted_frame_ids": {
        "items": {
          "format": "uuid",
          "type": "string"
        },
        "maxItems": 2,
        "title": "Persisted Frame Ids",
        "type": "array"
      }
    },
    "required": [
      "tenant_id",
      "project_id",
      "session_id",
      "fencing_token",
      "operation_id",
      "persisted_frame_ids"
    ],
    "title": "VisualWorkerAck",
    "type": "object"
  },
  "VisualWorkerOperationResult": {
    "additionalProperties": false,
    "properties": {
      "operation": {
        "$ref": "#/$defs/VisualOperation"
      },
      "frames": {
        "items": {
          "$ref": "#/$defs/VisualOperationFrame"
        },
        "maxItems": 2,
        "title": "Frames",
        "type": "array"
      },
      "locator": {
        "anyOf": [
          {
            "$ref": "#/$defs/VisualLocatorEvidence"
          },
          {
            "type": "null"
          }
        ]
      },
      "prepared_handle": {
        "format": "uuid",
        "title": "Prepared Handle",
        "type": "string"
      },
      "state_fingerprint": {
        "anyOf": [
          {
            "pattern": "^[a-f0-9]{64}$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "State Fingerprint"
      },
      "checkpoint": {
        "anyOf": [
          {
            "$ref": "#/$defs/VisualCheckpoint"
          },
          {
            "type": "null"
          }
        ]
      },
      "semantic_change": {
        "enum": [
          "changed",
          "unchanged",
          "unavailable"
        ],
        "title": "Semantic Change",
        "type": "string"
      },
      "duration_ms": {
        "maximum": 3600000,
        "minimum": 0,
        "title": "Duration Ms",
        "type": "integer"
      },
      "acknowledged": {
        "title": "Acknowledged",
        "type": "boolean"
      },
      "replayable": {
        "title": "Replayable",
        "type": "boolean"
      }
    },
    "required": [
      "operation",
      "frames",
      "locator",
      "prepared_handle",
      "state_fingerprint",
      "checkpoint",
      "semantic_change",
      "duration_ms",
      "acknowledged",
      "replayable"
    ],
    "title": "VisualWorkerOperationResult",
    "type": "object"
  }
};
